services:
  db:
    image: postgres:latest
    container_name: quiz_db
    volumes:
      - ./docker_info/postgresql_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - './docker_info/redis_data:/data'
    ports:
      - "6379:6379"
    restart: on-failure

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./docker_info/nats/data:/data"
    command: ["--jetstream", "--store_dir=/data"]

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    volumes:
      - "./docker_info/nui/db:/db"
    depends_on:
      - nats
