services:
  db:
    image: postgres:latest
    container_name: quiz_db
    volumes:
      - ./docker_info/postgresql_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - './docker_info/redis_data:/data'
    ports:
      - "6379:6379"
    restart: on-failure
