"""Change reply model

Revision ID: eaf6d1e5464a
Revises: f5eed00aaf8d
Create Date: 2025-06-08 21:40:23.842767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf6d1e5464a'
down_revision: Union[str, None] = 'f5eed00aaf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('replies', 'answer_text',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'answer_text',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('replies', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
