"""Add Reply model

Revision ID: f5eed00aaf8d
Revises: eeaa0d549c9d
Create Date: 2025-05-22 22:38:25.848963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5eed00aaf8d'
down_revision: Union[str, None] = 'eeaa0d549c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=128), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('finished_at', sa.DateTime(), nullable=False))
    op.drop_column('games', 'started_at')
    op.drop_column('results', 'success_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('games', 'finished_at')
    op.drop_table('replies')
    # ### end Alembic commands ###
