"""new

Revision ID: fff098e674fb
Revises: a18c7c41fc2f
Create Date: 2025-06-14 21:54:45.650746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff098e674fb'
down_revision: Union[str, None] = 'a18c7c41fc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('quizzes', sa.Column('is_opened', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quizzes', sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'is_closed')
    op.drop_column('quizzes', 'is_opened')
    op.alter_column('questions', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
